### ISSUE TITLE
What is lodash.first

### ISSUE THREAD

**Issue by chamuridis** [flowroute/jssip_client#11]
Cant understand why we  import first from 'lodash.first';   in file FlowrouteClient.js

**Comment by Mazuh** [comment]
hi!

for the "what" part, just read the docs: https://lodash.com/docs/#head

for the "can't understand" part: basically, it's an explicit and safer way to have an `arr[0]` value.

assuming that `first` is supposed to be just a light util, here are its differences:

```js
let foo = [1, 2, 3];
let bar = undefined; // very common runtime error on languages not well typed, just like NoneType errors in Python

foo[0]; // returns 1, but the code sounds unnecessarily "C-like"
bar[0]; // throws TypeError

first(foo); // returns 1, but explicit and friendly written, it's more meaningful
first(bar); // returns undefined instead of an error, leaving the rest of the code to handle what to do without "goto-like" flow changes or forcing client functions to handle unexpected errors (since JS doesn't suport checked exceptions like Java)
```

so [readability counts](https://www.python.org/dev/peps/pep-0020/) and it was a coding decision made at the time, but that can easily be undone in case of any bad issue shows up.

**Comment by Mazuh** [comment]
hope I answered you well enough! :smiley: if it was just a question, I'd ask you to close the issue if you're satisfied with the answer

but if you have an “actionable” feedback, please tell us. o/

**Comment by chamuridis** [comment]
Thank you for the big answer. Just realized what is lodash and i feel bad now for for my stupid question in such serious project. Thank you one more time for instead of laughing on me you made such of full answer. Also thank you for this repo, its really unique project. Right now i implementing multichannel phone. So phone users can put on hold calls and unhold back. For me its not so easy to implement this functionality especially when i realize that somebody already did this before me and i could just find his solution and use it. What i want to say is we and i personal waiting new features in this project, your doing greate job, the future is behind web softphones

**Comment by Mazuh** [comment]
nah, your question seemed serious, I'd never laugh on you!

now, going back to the features you're waiting, could you file up another issue describing exactly what is desired? I'll be glad to help you whenever I can regarding to webrtc on client side.

**Comment by chamuridis** [comment]
https://github.com/flowroute/jssip_client/issues/13
